name: Build
'on':
  - push
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: sudo apt install -y cmake gcc libglpk-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make

